# Generated by Django 3.1.3 on 2020-11-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('Available', 'Item Ready to purches'), ('Sold', 'Item Sold out already'), ('Restoking', 'Item restocking for few days')], default='Sold', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('Available', 'Item Ready to purches'), ('Sold', 'Item Sold out already'), ('Restoking', 'Item restocking for few days')], default='Sold', max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('Available', 'Item Ready to purches'), ('Sold', 'Item Sold out already'), ('Restoking', 'Item restocking for few days')], default='Sold', max_length=50),
        ),
    ]
